import { ScrollArea } from '../ui/scroll-area'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription
} from '../ui/dialog'

/**
 * Privacy policy content rendered as a scrollable block.
 * Used inside both the first-launch notice and the Settings dialog.
 */
export function PrivacyPolicyContent() {
  return (
    <div className="space-y-6 text-sm leading-relaxed">
      <section>
        <h3 className="mb-2 text-base font-semibold">What Open CoWork Does</h3>
        <p className="text-muted-foreground">
          Open CoWork is an AI assistant that runs on your computer. It connects to cloud-based AI
          models to process your conversations and can perform actions on your behalf, including
          running shell commands, reading and writing files, and automating a web browser.
        </p>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">AI Interaction Disclosure</h3>
        <p className="text-muted-foreground">
          All responses in Open CoWork are generated by artificial intelligence models, not by
          humans. The AI can make mistakes, produce inaccurate information, or misunderstand
          instructions. Always review AI-generated output before acting on it, especially for
          commands, code changes, or file modifications.
        </p>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">Data Sent to Third Parties</h3>
        <ul className="list-inside list-disc space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">OpenRouter</span> &mdash; Your
            conversation messages (prompts and AI responses) are sent to{' '}
            <a
              href="https://openrouter.ai/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              OpenRouter
            </a>
            , which routes them to the AI model provider you select (e.g., Anthropic, Google,
            OpenAI). Your API key authenticates these requests.
          </li>
          <li>
            <span className="font-medium text-foreground">AI Model Providers</span> &mdash;
            OpenRouter forwards your messages to the selected provider. Each provider has its own
            data handling policies. Consult the provider&apos;s privacy policy for details.
          </li>
          <li>
            <span className="font-medium text-foreground">PostHog Analytics</span> &mdash; If you
            opt in to analytics, anonymous usage events (feature usage, errors, performance metrics)
            are sent to{' '}
            <a
              href="https://posthog.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              PostHog
            </a>
            . No conversation content, code, or personal data is included. You can opt out at any
            time in Settings.
          </li>
          <li>
            <span className="font-medium text-foreground">Skill Registry</span> &mdash; Open CoWork
            fetches AI skill definitions from{' '}
            <a
              href="https://skillregistry.io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              skillregistry.io
            </a>
            . Skill content is loaded into the AI&apos;s context to guide its behavior. Browsing and
            installing skills sends requests to skillregistry.io.
          </li>
        </ul>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">Data Stored on Your Machine</h3>
        <ul className="list-inside list-disc space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">Conversations and messages</span> are
            stored in a local SQLite database on your computer. This data is not encrypted at rest.
          </li>
          <li>
            <span className="font-medium text-foreground">Tool call inputs and outputs</span>{' '}
            (shell commands, file operations, browser actions) are stored alongside conversations.
          </li>
          <li>
            <span className="font-medium text-foreground">Screenshots and images</span> captured
            during browser automation are stored locally.
          </li>
          <li>
            <span className="font-medium text-foreground">Your API key</span> is stored using your
            operating system&apos;s secure storage (Keychain on macOS, Credential Manager on
            Windows).
          </li>
          <li>
            <span className="font-medium text-foreground">Application settings</span> and
            preferences are stored in the local database.
          </li>
        </ul>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">AI Tool Execution</h3>
        <p className="text-muted-foreground">
          The AI can request to execute tools on your behalf, including running shell commands,
          reading and writing files on your filesystem, and controlling a web browser. Tool
          executions may produce side effects on your system. The outputs of these tools are included
          in the conversation context sent to the AI model provider.
        </p>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">Your Rights and Control</h3>
        <ul className="list-inside list-disc space-y-2 text-muted-foreground">
          <li>
            All conversation data is stored locally on your machine. You have full control over it.
          </li>
          <li>
            You can delete any conversation from within the app, or remove the entire database file
            to erase all data.
          </li>
          <li>You can opt out of analytics at any time in Settings.</li>
          <li>
            You can revoke your API key at any time, which stops all communication with OpenRouter.
          </li>
          <li>
            Open CoWork is open-source software. You can inspect exactly what data is sent and where
            by reviewing the source code.
          </li>
        </ul>
      </section>

      <section>
        <h3 className="mb-2 text-base font-semibold">Third-Party Privacy Policies</h3>
        <ul className="list-inside list-disc space-y-1 text-muted-foreground">
          <li>
            <a
              href="https://openrouter.ai/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              OpenRouter Privacy Policy
            </a>
          </li>
          <li>
            <a
              href="https://posthog.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              PostHog Privacy Policy
            </a>
          </li>
          <li>
            <a
              href="https://skillregistry.io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              Skill Registry (skillregistry.io)
            </a>
          </li>
        </ul>
      </section>
    </div>
  )
}

/**
 * Standalone dialog for viewing the full privacy policy from Settings.
 */
interface PrivacyPolicyDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function PrivacyPolicyDialog({ open, onOpenChange }: PrivacyPolicyDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg max-h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>Privacy Policy</DialogTitle>
          <DialogDescription>How Open CoWork handles your data</DialogDescription>
        </DialogHeader>
        <ScrollArea className="flex-1 pr-4" style={{ maxHeight: 'calc(80vh - 8rem)' }}>
          <PrivacyPolicyContent />
        </ScrollArea>
      </DialogContent>
    </Dialog>
  )
}
